// Temporary fallback translations for all languages
// This ensures all 14 languages work immediately

export const fallbackTranslation = {
  // Navigation
  'nav.technology': 'Technology',
  'nav.ecosystem': 'Ecosystem',
  'nav.roadmap': 'Roadmap',
  'nav.team': 'Team',
  'nav.documentation': 'Documentation',
  'nav.dashboard': 'Dashboard',
  'nav.signin': 'Sign In',
  'nav.getStarted': 'Get Started',
  'nav.launchApp': 'Launch App',

  // Homepage Hero
  'hero.title': 'The Future of Sustainable Energy Trading',
  'hero.subtitle': 'ENERGY Token - Powering the Soltolaria Ecosystem',
  'hero.description': 'Trade, stake, and earn with the world\'s most advanced renewable energy blockchain platform',
  'hero.launchApp': 'Launch App',
  'hero.learnMore': 'Learn More',
  'hero.visitPlatform': 'Visit Soltolaria Platform',
  'hero.tokenEconomics': 'Token Economics',
  'hero.auditedContract': 'Audited Smart Contract',
  'hero.holders': 'Holders',
  'hero.liveOn': 'Live on Solana',
  'hero.feature1': 'Powers all Soltolaria transactions',
  'hero.feature2': 'Stake for platform rewards',
  'hero.feature3': 'Governance voting rights',
  'hero.feature4': 'Fee discounts for traders',
  'hero.totalSupply': 'Total Supply',
  'hero.currentPrice': 'Current Price',
  'hero.marketCap': 'Market Cap',
  'hero.holdersCount': '50,000+ Holders',
  'hero.liveOnSolana': 'Live on Solana',
  'hero.networkStatus': 'Network Status',
  'hero.volume24h': '24h Volume',
  'hero.change24h': '24h Change',
  'hero.gasFee': 'Gas Fee',

  // Token Metrics
  'metrics.totalSupply': 'Total Supply',
  'metrics.currentPrice': 'Current Price',
  'metrics.marketCap': 'Market Cap',
  'metrics.holders': 'Holders',
  'metrics.24hVolume': '24h Volume',
  'metrics.24hChange': '24h Change',
  'metrics.gasFee': 'Gas Fee',
  'metrics.networkStatus': 'Network Status',

  // Features
  'features.title': 'Why Choose ENERGY Token?',
  'features.instant': 'Instant Transactions',
  'features.instantDesc': 'Lightning-fast trades on the Solana blockchain',
  'features.sustainable': 'Sustainable Future',
  'features.sustainableDesc': 'Supporting renewable energy projects worldwide',
  'features.rewards': 'Staking Rewards',
  'features.rewardsDesc': 'Earn up to 25% APY through our staking program',
  'features.secure': 'Bank-Grade Security',
  'features.secureDesc': 'Multi-signature wallets and advanced encryption',
  'features.powersTransactions': 'Powers all Soltolaria transactions',
  'features.stakeRewards': 'Stake for platform rewards',
  'features.governanceRights': 'Governance voting rights',
  'features.feeDiscounts': 'Fee discounts for traders',

  // Quick Navigation
  'quick.explore': 'Explore ENERGY Blockchain',
  'quick.technology': 'Technology',
  'quick.technologyDesc': 'Blockchain architecture',
  'quick.ecosystem': 'Ecosystem',
  'quick.ecosystemDesc': 'Network participants',
  'quick.roadmap': 'Roadmap',
  'quick.roadmapDesc': 'Development timeline',
  'quick.team': 'Team',
  'quick.teamDesc': 'Meet our experts',
  'quick.platformFeatures': 'Platform Features',
  'quick.liveStats': 'Live Stats',
  'quick.liveStatsDesc': 'Real-time metrics',
  'quick.energyTrading': 'Energy Trading',
  'quick.energyTradingDesc': 'Trade renewable energy',
  'quick.carbonCredits': 'Carbon Credits',
  'quick.carbonCreditsDesc': 'Offset emissions',
  'quick.features': 'Features',
  'quick.featuresDesc': 'Platform capabilities',
  'quicknav.techDesc': 'Blockchain architecture',
  'quicknav.ecoDesc': 'Network participants',
  'quicknav.roadmapDesc': 'Development timeline',
  'quicknav.teamDesc': 'Meet our experts',
  'quicknav.liveStats': 'Live Stats',
  'quicknav.liveStatsDesc': 'Real-time metrics',
  'quicknav.energyTrading': 'Energy Trading',
  'quicknav.energyTradingDesc': 'Trade renewable energy',
  'quicknav.carbonCredits': 'Carbon Credits',
  'quicknav.carbonCreditsDesc': 'Offset emissions',
  'quicknav.features': 'Features',
  'quicknav.featuresDesc': 'Platform capabilities',
  'quicknav.dashboardDesc': 'Manage portfolio',
  'quicknav.docsDesc': 'Developer guides',
  'quicknav.blog': 'Blog',
  'quicknav.blogDesc': 'Latest updates',

  // Footer
  'footer.quickLinks': 'Quick Links',
  'footer.technology': 'Technology',
  'footer.ecosystem': 'Ecosystem',
  'footer.roadmap': 'Roadmap',
  'footer.documentation': 'Documentation',
  'footer.blog': 'Blog',
  'footer.legal': 'Legal',
  'footer.privacy': 'Privacy Policy',
  'footer.terms': 'Terms of Service',
  'footer.cookies': 'Cookie Policy',
  'footer.compliance': 'Compliance',
  'footer.followUs': 'Follow Us',
  'footer.twitter': 'Twitter',
  'footer.telegram': 'Telegram',
  'footer.discord': 'Discord',
  'footer.github': 'GitHub',
  'footer.newsletter': 'Newsletter',
  'footer.newsletterDesc': 'Get the latest updates on ENERGY token',
  'footer.emailPlaceholder': 'Enter your email',
  'footer.subscribe': 'Subscribe',
  'footer.subscribing': 'Subscribing...',
  'footer.subscribeSuccess': 'Successfully subscribed!',
  'footer.allRights': 'All rights reserved',
  'footer.builtWith': 'Built with',
  'footer.by': 'by the ENERGY Token Team',
  'footer.energyDex': 'Energy DEX',
  'footer.carbonMarketplace': 'Carbon Marketplace',
  'footer.validatorNetwork': 'Validator Network',
  'footer.apiDocs': 'API Documentation',
  'footer.aboutUs': 'About Us',
  'footer.careers': 'Careers',
  'footer.pressKit': 'Press Kit',
  'footer.whitepaper': 'Whitepaper',
  'footer.technicalDocs': 'Technical Docs',
  'footer.developerGuide': 'Developer Guide',
  'footer.community': 'Community',
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.termsOfService': 'Terms of Service',
  'footer.cookiePolicy': 'Cookie Policy',
  'footer.description': 'The world\'s first renewable energy blockchain with 65,000+ TPS, carbon credits, and sustainable DeFi protocols. Building the future of clean energy trading.',
  'footer.globalNetwork': 'Global Network • Decentralized',

  // Auth
  'auth.welcomeBack': 'Welcome Back',
  'auth.signInDesc': 'Sign in to access your ENERGY dashboard',
  'auth.signInMessage': 'Sign in to access your ENERGY dashboard',
  'auth.email': 'Email',
  'auth.emailAddress': 'Email Address',
  'auth.emailPlaceholder': 'Enter your email',
  'auth.enterEmail': 'Enter your email',
  'auth.password': 'Password',
  'auth.passwordPlaceholder': 'Enter your password',
  'auth.enterPassword': 'Enter your password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.signIn': 'Sign In',
  'auth.signingIn': 'Signing In...',
  'auth.noAccount': "Don't have an account?",
  'auth.signUp': 'Sign up',
  'auth.orContinue': 'Or continue with',
  'auth.google': 'Google',
  'auth.twitter': 'Twitter',
  'auth.wallet': 'Wallet',
  'auth.connectWallet': 'Connect Wallet',
  'auth.webLogin': 'Web Login',
  'auth.emailRequired': 'Email is required',
  'auth.passwordRequired': 'Password is required',
  'auth.invalidCredentials': 'Invalid email or password',
  'auth.createAccount': 'Create Your Account',
  'auth.joinDesc': 'Join thousands of traders on ENERGY platform',
  'auth.fullName': 'Full Name',
  'auth.fullNamePlaceholder': 'Enter your full name',
  'auth.confirmPassword': 'Confirm Password',
  'auth.confirmPasswordPlaceholder': 'Confirm your password',
  'auth.agreeTerms': 'I agree to the',
  'auth.and': 'and',
  'auth.termsOfService': 'Terms of Service',
  'auth.privacyPolicy': 'Privacy Policy',
  'auth.createAccountBtn': 'Create Account',
  'auth.alreadyHaveAccount': 'Already have an account?',
  'auth.passwordStrength': 'Password Strength',
  'auth.weak': 'Weak',
  'auth.medium': 'Medium',
  'auth.strong': 'Strong',
  'auth.passwordMatch': 'Passwords match',
  'auth.passwordMismatch': 'Passwords do not match',
  'auth.walletComingSoon': 'Wallet connection feature coming soon!',
  'auth.feature1': 'Real-time portfolio tracking',
  'auth.feature2': 'Advanced trading tools',
  'auth.feature3': 'Staking rewards up to 25% APY',
  'auth.feature4': 'Exclusive member benefits',

  // Dashboard
  'dashboard.welcome': 'Welcome to your Dashboard',
  'dashboard.overview': 'Overview',
  'dashboard.portfolio': 'Portfolio',
  'dashboard.trading': 'Trading',
  'dashboard.staking': 'Staking',
  'dashboard.analytics': 'Analytics',
  'dashboard.totalValue': 'Total Value',
  'dashboard.energyBalance': 'ENERGY Balance',
  'dashboard.stakingRewards': 'Staking Rewards',
  'dashboard.carbonCredits': 'Carbon Credits',
  'dashboard.solarEnergy': 'Solar Energy',
  'dashboard.windEnergy': 'Wind Energy',
  'dashboard.hydroEnergy': 'Hydro Energy',
  'dashboard.naturalGas': 'Natural Gas',
  'dashboard.welcomeUser': 'Welcome, {name}',
  'dashboard.settings': 'Settings',
  'dashboard.history': 'History',
  'dashboard.notifications': 'Notifications',
  'dashboard.profile': 'Profile',
  'dashboard.logout': 'Logout',
  'dashboard.totalBalance': 'Total Balance',
  'dashboard.availableBalance': 'Available Balance',
  'dashboard.stakedAmount': 'Staked Amount',
  'dashboard.rewards': 'Rewards',
  'dashboard.hideBalance': 'Hide Balance',
  'dashboard.showBalance': 'Show Balance',
  'dashboard.recentTransactions': 'Recent Transactions',
  'dashboard.noTransactions': 'No transactions yet',
  'dashboard.viewAll': 'View All',
  'dashboard.quickActions': 'Quick Actions',
  'dashboard.buy': 'Buy',
  'dashboard.sell': 'Sell',
  'dashboard.send': 'Send',
  'dashboard.receive': 'Receive',
  'dashboard.stake': 'Stake',
  'dashboard.unstake': 'Unstake',
  'dashboard.swap': 'Swap',
  'dashboard.performance': 'Portfolio Performance',
  'dashboard.marketOverview': 'Market Overview',
  'dashboard.portfolioValue': 'Portfolio Value',
  'dashboard.change24h': '24h Change',
  'dashboard.vs': 'vs',
  'dashboard.last': 'last',
  'dashboard.high': 'High',
  'dashboard.low': 'Low',
  'dashboard.volume': 'Volume',
  'dashboard.energyAssets': 'Energy Assets',
  'dashboard.viewAllAssets': 'View All Assets',
  'dashboard.stakingPools': 'Staking Pools',
  'dashboard.apy': 'APY',
  'dashboard.tvl': 'TVL',
  'dashboard.yourStake': 'Your Stake',
  'dashboard.claimRewards': 'Claim Rewards',
  'dashboard.stakeMore': 'Stake More',
  'dashboard.type': 'Type',
  'dashboard.asset': 'Asset',
  'dashboard.amount': 'Amount',
  'dashboard.price': 'Price',
  'dashboard.total': 'Total',
  'dashboard.time': 'Time',
  'dashboard.status': 'Status',
  'dashboard.completed': 'Completed',
  'dashboard.pending': 'Pending',
  'dashboard.failed': 'Failed',
  'dashboard.refreshData': 'Refresh',
  'dashboard.exportCsv': 'Export CSV',
  'dashboard.viewAllTransactions': 'View All Transactions',
  'dashboard.lockPeriod': 'Lock Period',
  'dashboard.solarValidatorsPool': 'Solar Validators Pool',
  'dashboard.windEnergyPool': 'Wind Energy Pool',
  'dashboard.carbonCreditPool': 'Carbon Credit Pool',
  'dashboard.days': 'days',

  // Membership
  'membership.title': 'Choose Your Plan',
  'membership.subtitle': 'Unlock the full potential of ENERGY trading with our membership tiers',
  'membership.monthly': 'Monthly',
  'membership.yearly': 'Yearly',
  'membership.yearlyDiscount': 'Save 20%',
  'membership.starter': 'Starter',
  'membership.growth': 'Growth',
  'membership.professional': 'Professional',
  'membership.enterprise': 'Enterprise',
  'membership.most-popular': 'Most Popular',
  'membership.free': 'Free',
  'membership.forever': 'Forever',
  'membership.month': '/month',
  'membership.yearBilled': '/month (billed yearly)',
  'membership.selectPlan': 'Select Plan',
  'membership.currentPlan': 'Current Plan',
  'membership.upgrade': 'Upgrade',
  'membership.downgrade': 'Downgrade',
  'membership.contact': 'Contact Sales',
  'membership.basicDashboard': 'Basic Dashboard Access',
  'membership.portfolioTracking': 'Portfolio Tracking',
  'membership.marketData': 'Market Data',
  'membership.tradeExecution': 'Trade Execution',
  'membership.educationalResources': 'Educational Resources',
  'membership.communityForum': 'Community Forum Access',
  'membership.mobileApp': 'Mobile App Access',
  'membership.emailSupport': 'Email Support',
  'membership.advancedAnalytics': 'Advanced Analytics',
  'membership.apiAccess': 'API Access',
  'membership.prioritySupport': 'Priority Support',
  'membership.customAlerts': 'Custom Alerts',
  'membership.taxReports': 'Tax Reports',
  'membership.stakingBoost': 'Staking Rewards Boost',
  'membership.earlyAccess': 'Early Access Features',
  'membership.included': 'Included',
  'membership.notIncluded': 'Not Included',
  'membership.upTo3Assets': 'Up to 3 assets',
  'membership.upTo20Assets': 'Up to 20 assets',
  'membership.unlimited': 'Unlimited',
  'membership.delayed15min': 'Delayed 15 min',
  'membership.realTime': 'Real-time',
  'membership.10trades': '10 trades/month',
  'membership.100trades': '100 trades/month',
  'membership.500trades': '500 trades/month',
  'membership.unlimitedTrades': 'Unlimited trades',
  'membership.72hrResponse': '72hr response',
  'membership.24hrResponse': '24hr response',
  'membership.1hrResponse': '1hr response',
  'membership.phoneSupport': 'Phone & Chat Support',
  'membership.dedicatedManager': 'Dedicated Account Manager',
  'membership.5boost': '5% boost',
  'membership.10boost': '10% boost',
  'membership.15boost': '15% boost',
  'membership.starterDesc': 'Perfect for beginners exploring renewable energy trading',
  'membership.growthDesc': 'For active traders ready to scale their portfolio',
  'membership.professionalDesc': 'Advanced tools for serious energy traders',
  'membership.enterpriseDesc': 'Complete solution for institutional trading',
  'membership.starterBenefit1': 'Access to basic trading features',
  'membership.starterBenefit2': 'Learn with educational content',
  'membership.starterBenefit3': 'Join our growing community',
  'membership.growthBenefit1': 'Real-time market data access',
  'membership.growthBenefit2': 'Advanced portfolio analytics',
  'membership.growthBenefit3': 'Priority customer support',
  'membership.professionalBenefit1': 'API access for automated trading',
  'membership.professionalBenefit2': 'Comprehensive tax reporting',
  'membership.professionalBenefit3': 'Enhanced staking rewards',
  'membership.enterpriseBenefit1': 'White-label trading solutions',
  'membership.enterpriseBenefit2': 'Dedicated account management',
  'membership.enterpriseBenefit3': 'Custom feature development',
  'membership.faq': 'Frequently Asked Questions',
  'membership.compareFeatures': 'Compare Features',
  'membership.backToDashboard': 'Back to Dashboard',

  // Trading
  'trading.title': 'Trading',
  'trading.orderBook': 'Order Book',
  'trading.recentTrades': 'Recent Trades',
  'trading.placeOrder': 'Place Order',
  'trading.buy': 'Buy',
  'trading.sell': 'Sell',
  'trading.limit': 'Limit',
  'trading.market': 'Market',
  'trading.stopLimit': 'Stop Limit',
  'trading.price': 'Price',
  'trading.amount': 'Amount',
  'trading.total': 'Total',
  'trading.available': 'Available',
  'trading.openOrders': 'Open Orders',
  'trading.orderHistory': 'Order History',
  'trading.cancelAll': 'Cancel All',
  'trading.pair': 'Trading Pair',
  'trading.side': 'Side',
  'trading.status': 'Status',
  'trading.filled': 'Filled',
  'trading.time': 'Time',
  'trading.cancel': 'Cancel',
  'trading.orderPlaced': 'Order Placed Successfully',
  'trading.orderCancelled': 'Order Cancelled',
  'trading.insufficientFunds': 'Insufficient Funds',
  'trading.minOrder': 'Minimum Order Amount',
  'trading.maxOrder': 'Maximum Order Amount',

  // Settings
  'settings.title': 'Settings',
  'settings.profile': 'Profile',
  'settings.security': 'Security',
  'settings.notifications': 'Notifications',
  'settings.appearance': 'Appearance',
  'settings.api': 'API Keys',
  'settings.wallet': 'Wallet',
  'settings.save': 'Save Changes',
  'settings.saving': 'Saving...',
  'settings.saved': 'Settings Saved',
  'settings.cancel': 'Cancel',
  'settings.personalInfo': 'Personal Information',
  'settings.username': 'Username',
  'settings.emailAddress': 'Email Address',
  'settings.phoneNumber': 'Phone Number',
  'settings.country': 'Country',
  'settings.language': 'Language',
  'settings.timezone': 'Timezone',
  'settings.bio': 'Bio',
  'settings.avatar': 'Avatar',
  'settings.uploadAvatar': 'Upload Avatar',
  'settings.changePassword': 'Change Password',
  'settings.currentPassword': 'Current Password',
  'settings.newPassword': 'New Password',
  'settings.confirmNewPassword': 'Confirm New Password',
  'settings.twoFactor': 'Two-Factor Authentication',
  'settings.enable2FA': 'Enable 2FA',
  'settings.disable2FA': 'Disable 2FA',
  'settings.sessions': 'Active Sessions',
  'settings.terminateAll': 'Terminate All Sessions',
  'settings.theme': 'Theme',
  'settings.darkMode': 'Dark Mode',
  'settings.lightMode': 'Light Mode',
  'settings.systemMode': 'System',
  'settings.emailNotifications': 'Email Notifications',
  'settings.pushNotifications': 'Push Notifications',
  'settings.tradingAlerts': 'Trading Alerts',
  'settings.priceAlerts': 'Price Alerts',
  'settings.newsUpdates': 'News Updates',
  'settings.createApiKey': 'Create API Key',
  'settings.apiKeyName': 'API Key Name',
  'settings.permissions': 'Permissions',
  'settings.readOnly': 'Read Only',
  'settings.trading': 'Trading',
  'settings.withdrawal': 'Withdrawal',

  // Admin
  'admin.dashboard': 'Admin Dashboard',
  'admin.controlPanel': 'ENERGY Token Control Panel',
  'admin.overview': 'Overview',
  'admin.users': 'Users',
  'admin.content': 'Content',
  'admin.analytics': 'Analytics',
  'admin.security': 'Security',
  'admin.system': 'System',
  'admin.totalUsers': 'Total Users',
  'admin.activeUsers': 'Active Users',
  'admin.totalRevenue': 'Total Revenue',
  'admin.transactions': 'Transactions',
  'admin.systemHealth': 'System Health',
  'admin.serverLoad': 'Server Load',
  'admin.storageUsed': 'Storage Used',
  'admin.recentActivity': 'Recent Activity',
  'admin.restrictedAccess': 'Restricted Access',
  'admin.adminOnly': 'This area is for authorized administrators only',
  'admin.logout': 'Logout',

  // Pages
  'pages.technology': 'Technology',
  'pages.ecosystem': 'Ecosystem',
  'pages.roadmap': 'Roadmap',
  'pages.team': 'Team',
  'pages.documentation': 'Documentation',
  'pages.blog': 'Blog',
  'pages.features': 'Features',
  'pages.whitepaper': 'Whitepaper',
  'pages.careers': 'Careers',
  'pages.press': 'Press',
  'pages.developers': 'Developers',
  'pages.support': 'Support',
  'pages.about': 'About',
  'pages.contact': 'Contact',
  'pages.legal': 'Legal',
  'pages.privacy': 'Privacy Policy',
  'pages.terms': 'Terms of Service',
  'pages.cookies': 'Cookie Policy',
  'pages.energyTrading': 'Energy Trading',
  'pages.carbonCredits': 'Carbon Credits',
  'pages.dex': 'Energy DEX',
  'pages.marketplace': 'Marketplace',
  'pages.validators': 'Validators',
  'pages.governance': 'Governance',

  // Forms
  'forms.required': 'Required',
  'forms.optional': 'Optional',
  'forms.pleaseSelect': 'Please select',
  'forms.enterValue': 'Enter value',
  'forms.chooseFile': 'Choose File',
  'forms.noFileChosen': 'No file chosen',
  'forms.fileUploaded': 'File uploaded successfully',
  'forms.uploadFailed': 'Upload failed',
  'forms.invalidFormat': 'Invalid format',
  'forms.tooLarge': 'File too large',
  'forms.tooSmall': 'File too small',
  'forms.processing': 'Processing...',
  'forms.submit': 'Submit',
  'forms.submitting': 'Submitting...',
  'forms.submitted': 'Submitted successfully',
  'forms.failed': 'Submission failed',

  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.warning': 'Warning',
  'common.info': 'Info',
  'common.confirm': 'Confirm',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.refresh': 'Refresh',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.export': 'Export',
  'common.import': 'Import',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.copy': 'Copy',
  'common.copied': 'Copied!',
  'common.share': 'Share',
  'common.print': 'Print',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.submit': 'Submit',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.previous': 'Previous',
  'common.finish': 'Finish',
  'common.skip': 'Skip',
  'common.retry': 'Retry',
  'common.viewMore': 'View More',
  'common.viewLess': 'View Less',
  'common.showMore': 'Show More',
  'common.showLess': 'Show Less',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.ok': 'OK',
  'common.select': 'Select',
  'common.selectAll': 'Select All',
  'common.unselectAll': 'Unselect All',
  'common.clear': 'Clear',
  'common.clearAll': 'Clear All',
  'common.notification': 'Notification',
  'common.message': 'Message',
  'common.alert': 'Alert',
  'common.update': 'Update',
  'common.create': 'Create',
  'common.add': 'Add',
  'common.remove': 'Remove',
  'common.connect': 'Connect',
  'common.disconnect': 'Disconnect',
  'common.online': 'Online',
  'common.offline': 'Offline',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.public': 'Public',
  'common.private': 'Private'
};