// Temporary fallback translations for all languages
// This ensures all 14 languages work immediately

export const fallbackTranslation = {
  // Navigation
  'nav.technology': 'Technology',
  'nav.ecosystem': 'Ecosystem',
  'nav.roadmap': 'Roadmap',
  'nav.team': 'Team',
  'nav.documentation': 'Documentation',
  'nav.dashboard': 'Dashboard',
  'nav.signin': 'Sign In',
  'nav.getStarted': 'Get Started',
  'nav.launchApp': 'Launch App',

  // Homepage Hero
  'hero.title': 'The Future of Sustainable Energy Trading',
  'hero.subtitle': 'ENERGY Token - Powering the Soltolaria Ecosystem',
  'hero.description': 'Trade, stake, and earn with the world\'s most advanced renewable energy blockchain platform',
  'hero.launchApp': 'Launch App',
  'hero.learnMore': 'Learn More',
  'hero.visitPlatform': 'Visit Soltolaria Platform',
  'hero.tokenEconomics': 'Token Economics',
  'hero.auditedContract': 'Audited Smart Contract',
  'hero.holders': 'Holders',
  'hero.liveOn': 'Live on Solana',
  'hero.feature1': 'Powers all Soltolaria transactions',
  'hero.feature2': 'Stake for platform rewards',
  'hero.feature3': 'Governance voting rights',
  'hero.feature4': 'Fee discounts for traders',
  'hero.totalSupply': 'Total Supply',
  'hero.currentPrice': 'Current Price',
  'hero.marketCap': 'Market Cap',
  'hero.holdersCount': '50,000+ Holders',
  'hero.liveOnSolana': 'Live on Solana',
  'hero.networkStatus': 'Network Status',
  'hero.volume24h': '24h Volume',
  'hero.change24h': '24h Change',
  'hero.gasFee': 'Gas Fee',

  // Quick Navigation
  'quick.explore': 'Explore ENERGY Blockchain',
  'quicknav.techDesc': 'Blockchain architecture',
  'quicknav.ecoDesc': 'Network participants',
  'quicknav.roadmapDesc': 'Development timeline',
  'quicknav.teamDesc': 'Meet our experts',
  'quicknav.liveStats': 'Live Stats',
  'quicknav.liveStatsDesc': 'Real-time metrics',
  'quicknav.energyTrading': 'Energy Trading',
  'quicknav.energyTradingDesc': 'Trade renewable energy',
  'quicknav.carbonCredits': 'Carbon Credits',
  'quicknav.carbonCreditsDesc': 'Offset emissions',
  'quicknav.features': 'Features',
  'quicknav.featuresDesc': 'Platform capabilities',
  'quicknav.dashboardDesc': 'Manage portfolio',
  'quicknav.docsDesc': 'Developer guides',
  'quicknav.blog': 'Blog',
  'quicknav.blogDesc': 'Latest updates',

  // Footer
  'footer.energyDex': 'Energy DEX',
  'footer.carbonMarketplace': 'Carbon Marketplace',
  'footer.validatorNetwork': 'Validator Network',
  'footer.apiDocs': 'API Documentation',
  'footer.aboutUs': 'About Us',
  'footer.careers': 'Careers',
  'footer.pressKit': 'Press Kit',
  'footer.whitepaper': 'Whitepaper',
  'footer.technicalDocs': 'Technical Docs',
  'footer.developerGuide': 'Developer Guide',
  'footer.community': 'Community',
  'footer.privacyPolicy': 'Privacy Policy',
  'footer.termsOfService': 'Terms of Service',
  'footer.cookiePolicy': 'Cookie Policy',
  'footer.description': 'The world\'s first renewable energy blockchain with 65,000+ TPS, carbon credits, and sustainable DeFi protocols. Building the future of clean energy trading.',
  'footer.globalNetwork': 'Global Network • Decentralized',

  // Auth
  'auth.welcomeBack': 'Welcome Back',
  'auth.signInMessage': 'Sign in to access your ENERGY dashboard',
  'auth.email': 'Email',
  'auth.emailAddress': 'Email Address',
  'auth.enterEmail': 'Enter your email',
  'auth.password': 'Password',
  'auth.enterPassword': 'Enter your password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.walletComingSoon': 'Wallet connection feature coming soon!',
  'auth.feature1': 'Real-time portfolio tracking',
  'auth.feature2': 'Advanced trading tools',
  'auth.feature3': 'Staking rewards up to 25% APY',
  'auth.feature4': 'Exclusive member benefits',

  // Dashboard
  'dashboard.overview': 'Overview',
  'dashboard.portfolio': 'Portfolio',
  'dashboard.trading': 'Trading',
  'dashboard.staking': 'Staking',
  'dashboard.analytics': 'Analytics',
  'dashboard.totalValue': 'Total Value',
  'dashboard.energyBalance': 'ENERGY Balance',
  'dashboard.stakingRewards': 'Staking Rewards',
  'dashboard.carbonCredits': 'Carbon Credits',
  'dashboard.solarEnergy': 'Solar Energy',
  'dashboard.windEnergy': 'Wind Energy',
  'dashboard.hydroEnergy': 'Hydro Energy',
  'dashboard.naturalGas': 'Natural Gas'
};